title: "News Snippet Generation"
author: 
- SnipAId Team
- Hannah Greven
- Benjamin Rech
description: "A Learning Journey on Open Source Large Language Models and how to assist journalists with generative AI in German" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media links used by the minima theme:
minima:
  social_links:
    - platform: github
      user_url: "https://github.com/snipaid-nlg"
      title: snipaid-nlg
    - platform: website # custom
      user_url: "https://snipaid.tech"
      title: snipaid.tech

# Custom Demo website
demo_website: 
   name: snipaid.tech
   url: https://snipaid.tech

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

#show_excerpts: true

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
